export type Platform = 'phone' | 'tv' | 'vr';
export type PlatformOverride = Platform | 'auto';
export type Version = { packageName: string; title: string; versionCode: string; versionName: string; size: number; minSdk: number; abis: string[]; tv: boolean; vr: boolean; platform: Platform; platformOverride: PlatformOverride; sha256: string; certificates: string[]; filename: string; addedAt: string; icon?: string; downloadUrl: string };
export type App = { packageName: string; title: string; icon?: string; versions: Version[] };
export type Transfer = { id: string; title: string; device: string; bytes: number; size: number; status: string; startedAt: string };
export type SendFile = { id: string; name: string; size: number };
export type FileTransfer = SendFile & { deviceId: string; device: string; sha256: string; bytes: number; status: 'queued' | 'receiving' | 'completed' | 'failed' | 'cancelled'; error: string; startedAt: string };
export type ConnectedDevice = { canReceiveFiles?: boolean; id: string; name: string; platform: Platform | 'unknown'; address: string; lastSeen: string };
export type State = { fileTransfers?: FileTransfer[]; devices: ConnectedDevice[]; apps: App[]; folder: string; errors: { file: string; message: string }[]; scanning: boolean; lastScan: string | null; serverId: string; running: boolean; port: number; addresses: string[]; transfers: Transfer[]; serverError?: string; discoveryError?: string; openAtLogin: boolean; sdk: string; preview: boolean };
declare global { interface Window { sibi: { stageFiles(files: File[]): Promise<SendFile[]>; chooseSendFiles(): Promise<SendFile[]>; sendFiles(ids: string[], targets: string[]): Promise<State>; fileTransferAction(id: string, action: 'cancel' | 'retry'): Promise<State>; snapshot(): Promise<State>; rescan(): Promise<State>; setPlatformOverride(hash: string, platform: PlatformOverride): Promise<State>; openFolder(): Promise<void>; reveal(hash: string): Promise<void>; chooseFolder(): Promise<State | undefined>; chooseSdk(): Promise<void>; server(running: boolean): Promise<void>; login(enabled: boolean): Promise<void>; copyAddress(): Promise<void>; onChange(fn: (s: State) => void): () => void } } }
