plugins { id 'com.android.library'; id 'org.jetbrains.kotlin.android' }
android {
    namespace 'com.sibi.store.core'
    compileSdk 35
    defaultConfig { minSdk 26 }
    buildFeatures { compose true; buildConfig true }
    composeOptions { kotlinCompilerExtensionVersion '1.5.1' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    kotlinOptions { jvmTarget = '17' }
}
dependencies {
    api 'androidx.core:core-ktx:1.12.0'
    api 'androidx.activity:activity-compose:1.9.3'
    api 'androidx.compose.ui:ui:1.5.4'
    api 'androidx.compose.foundation:foundation:1.5.4'
    api 'androidx.compose.material3:material3:1.2.1'
    api 'androidx.compose.material:material-icons-extended:1.5.4'
    api 'androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0'
    api 'androidx.work:work-runtime-ktx:2.9.0'
    api 'com.squareup.okhttp3:okhttp:4.12.0'
    api 'io.coil-kt:coil-compose:2.5.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
}
