const { _electron: electron } = require('playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
(async () => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'sibi-visual-'));
  const client = await electron.launch({ args: ['.', '--design-preview'], env: { ...process.env, SIBI_DATA_DIR: temp }, timeout: 60000 });
  try {
    const page = await client.firstWindow(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.getByRole('heading',{name:'App library'}).waitFor();
    await page.getByRole('heading',{name:'Version history'}).waitFor();
    await fs.mkdir('test-results',{recursive:true});
    const libraryTile = page.getByRole('button',{name:'Library',exact:true}).locator('svg rect').first();
    assert.equal(await libraryTile.evaluate(el => getComputedStyle(el).fill), 'rgb(255, 193, 7)', 'Active Library squares must be filled gold like the reference');
    const openFolderIcon = page.getByRole('button',{name:'Open folder',exact:true}).locator('svg');
    assert.equal(await openFolderIcon.evaluate(el => getComputedStyle(el).fill), 'rgb(8, 8, 8)', 'Primary folder icon must be filled black');
    const selected = page.locator('tbody tr.selected');
    const selectionBackground = await selected.evaluate(el => getComputedStyle(el).backgroundImage);
    await selected.hover();
    assert.notEqual(selectionBackground,'none');
    assert.equal(await selected.evaluate(el => getComputedStyle(el).backgroundImage),selectionBackground,'Selected gold highlight must remain visible on hover');
    await page.screenshot({path:'test-results/mac-library.png'});
    const filters = page.getByRole('group',{name:'Filter by platform'});
    await filters.getByRole('button',{name:'Phone'}).click();
    assert.equal(await page.locator('tbody tr').count(),3);
    assert.equal(await page.locator('tbody tr').filter({hasText:'VLC'}).count(),0);
    await page.getByRole('textbox',{name:'Search apps'}).fill('VLC');
    await page.getByText('No matching apps').waitFor();
    await filters.getByRole('button',{name:'TV',exact:false}).click();
    assert.equal(await page.locator('tbody tr').count(),1);
    await page.getByRole('textbox',{name:'Search apps'}).fill('');
    assert.equal(await page.locator('tbody tr').count(),3);
    await page.screenshot({path:'test-results/mac-tv-filter.png'});
    await filters.getByRole('button',{name:'VR',exact:false}).click();
    assert.equal(await page.locator('tbody tr').count(),1);
    assert.equal(await page.locator('tbody tr').filter({hasText:'Kodi'}).count(),1);
    const override = page.getByRole('combobox',{name:'Platform override for 21.2'});
    await override.selectOption('phone');
    await page.getByText('No VR apps').waitFor();
    await filters.getByRole('button',{name:'Phone',exact:false}).click();
    assert.equal(await page.locator('tbody tr').count(),4);
    await page.locator('tbody tr').filter({hasText:'Kodi'}).click();
    await page.getByRole('combobox',{name:'Platform override for 21.2'}).selectOption('auto');
    await page.waitForFunction(() => document.querySelectorAll('tbody tr').length === 3);
    assert.equal(await page.locator('tbody tr').count(),3);
    await filters.getByRole('button',{name:'VR',exact:false}).click();
    assert.equal(await page.locator('tbody tr').count(),1);
    await page.screenshot({path:'test-results/mac-vr-filter.png'});
    await filters.getByRole('button',{name:'All'}).focus();
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('tbody tr').count(),7);
    await page.getByRole('textbox',{name:'Search apps'}).fill('VLC');
    assert.equal(await page.locator('tbody tr').count(),1);
    await page.getByRole('textbox',{name:'Search apps'}).fill('no-such-app');
    await page.getByText('No matching apps').waitFor();
    await page.getByRole('button',{name:'Devices',exact:true}).click();
    await page.getByRole('heading',{name:'No connected devices'}).waitFor();
    const snapshot = await page.evaluate(() => window.sibi.snapshot());
    for (const [id, name, platform] of [['quest-preview', 'Quest 3', 'vr'], ['phone-preview', 'Pixel phone', 'phone']]) {
      const response = await fetch(`http://127.0.0.1:${snapshot.port}/api/v1/catalog?platform=phone`, { headers: { 'X-Device-Id': id, 'X-Device-Name': name, 'X-Device-Platform': platform, 'X-Device-Token': id.repeat(4), 'X-Device-Capabilities': 'files-v1' } });
      assert.equal(response.status, 200);
    }
    await page.getByText('Quest 3', {exact:true}).waitFor();
    await page.getByText('Pixel phone', {exact:true}).waitFor();
    assert.equal(await page.locator('.transfer-row').count(), 2);
    await page.screenshot({path:'test-results/mac-devices.png'});
    const sendPaths = [path.join(temp,'notes.txt'),path.join(temp,'image.bin')];
    await fs.writeFile(sendPaths[0],'Sibi transfer QA'); await fs.writeFile(sendPaths[1],Buffer.from([0,1,2,3]));
    await client.evaluate(({dialog}, paths) => { dialog.showOpenDialog = async () => ({canceled:false,filePaths:paths}); }, sendPaths);
    await page.getByRole('button',{name:'Send files',exact:true}).click();
    await page.getByRole('button',{name:'Choose files',exact:true}).click();
    await page.getByText('notes.txt',{exact:true}).waitFor();
    await page.locator('nav').getByRole('button',{name:/^Devices/}).click();
    await page.evaluate(() => { const input=document.createElement('input');input.type='file';input.multiple=true;input.id='qa-drop-files';input.style.display='none';document.body.appendChild(input); });
    await page.locator('#qa-drop-files').setInputFiles(sendPaths);
    await page.evaluate(() => { const input=document.getElementById('qa-drop-files'); const data=new DataTransfer(); for(const file of input.files)data.items.add(file);document.querySelector('.desktop').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}));input.remove(); });
    await page.getByRole('heading',{name:'Send files',exact:true}).waitFor();
    await page.getByText('notes.txt',{exact:true}).waitFor();
    await page.getByRole('checkbox',{name:/Quest 3/}).check();
    await page.getByRole('checkbox',{name:/Pixel phone/}).check();
    await page.getByRole('button',{name:'Send 2 files to 2 devices',exact:true}).click();
    await page.waitForFunction(() => document.querySelectorAll('.file-delivery').length===4);
    const inboxHeaders = {'X-Device-Id':'quest-preview','X-Device-Token':'quest-preview'.repeat(4)};
    const inbox = await fetch(`http://127.0.0.1:${snapshot.port}/api/v1/inbox`,{headers:inboxHeaders}).then(r=>r.json());
    assert.equal(inbox.files.length,2);
    const offer=inbox.files.find(f=>f.name==='notes.txt');
    const received=await fetch(`http://127.0.0.1:${snapshot.port}${offer.downloadUrl}`,{headers:inboxHeaders}).then(r=>r.text());
    assert.equal(received,'Sibi transfer QA');
    await fetch(`http://127.0.0.1:${snapshot.port}/api/v1/inbox/${offer.id}/status`,{method:'POST',headers:{...inboxHeaders,'Content-Type':'application/json'},body:JSON.stringify({status:'completed',bytes:offer.size})});
    await page.getByText('Saved on device',{exact:true}).waitFor();
    await page.locator('.file-delivery').filter({hasText:'To Pixel phone'}).first().getByRole('button',{name:'Cancel',exact:true}).click();
    await page.getByText('cancelled',{exact:true}).waitFor();
    await page.screenshot({path:'test-results/mac-send-files.png'});
    await page.getByRole('button',{name:'Settings',exact:true}).click();
    await page.getByRole('heading',{name:'Local server'}).waitFor();
    await page.screenshot({path:'test-results/mac-settings.png'});
    await page.getByRole('button',{name:'Stop server',exact:true}).click();
    await page.getByRole('button',{name:'Start server',exact:true}).waitFor();
    await page.getByRole('button',{name:'Start server',exact:true}).click();
    await page.getByRole('button',{name:'Stop server',exact:true}).waitFor();
    await page.getByRole('button',{name:'Devices',exact:true}).click();
    await page.getByRole('heading',{name:'No connected devices'}).waitFor();
    assert.deepEqual(errors,[]);
    console.log('Electron UI: search, empty results, selection, settings and server stop/start passed.');
  } finally { await client.close(); await fs.rm(temp,{recursive:true,force:true}); }
})().catch(e=>{console.error(e);process.exitCode=1;});
