const { _electron: electron } = require('playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
(async () => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'sibi-visual-'));
  const client = await electron.launch({ args: ['.', '--design-preview'], env: { ...process.env, SIBI_DATA_DIR: temp }, timeout: 60000 });
  try {
    const page = await client.firstWindow(); const errors = []; page.on('pageerror', e => errors.push(e.message));
    await page.getByRole('heading',{name:'App library'}).waitFor();
    await page.getByRole('heading',{name:'Version history'}).waitFor();
    await fs.mkdir('test-results',{recursive:true});
    const libraryTile = page.getByRole('button',{name:'Library',exact:true}).locator('svg rect').first();
    assert.equal(await libraryTile.evaluate(el => getComputedStyle(el).fill), 'rgb(255, 193, 7)', 'Active Library squares must be filled gold like the reference');
    const openFolderIcon = page.getByRole('button',{name:'Open folder',exact:true}).locator('svg');
    assert.equal(await openFolderIcon.evaluate(el => getComputedStyle(el).fill), 'rgb(8, 8, 8)', 'Primary folder icon must be filled black');
    const selected = page.locator('tbody tr.selected');
    const selectionBackground = await selected.evaluate(el => getComputedStyle(el).backgroundImage);
    await selected.hover();
    assert.notEqual(selectionBackground,'none');
    assert.equal(await selected.evaluate(el => getComputedStyle(el).backgroundImage),selectionBackground,'Selected gold highlight must remain visible on hover');
    await page.screenshot({path:'test-results/mac-library.png'});
    const filters = page.getByRole('group',{name:'Filter by platform'});
    await filters.getByRole('button',{name:'Phone'}).click();
    assert.equal(await page.locator('tbody tr').count(),3);
    assert.equal(await page.locator('tbody tr').filter({hasText:'VLC'}).count(),0);
    await page.getByRole('textbox',{name:'Search apps'}).fill('VLC');
    await page.getByText('No matching apps').waitFor();
    await filters.getByRole('button',{name:'TV',exact:false}).click();
    assert.equal(await page.locator('tbody tr').count(),1);
    await page.getByRole('textbox',{name:'Search apps'}).fill('');
    assert.equal(await page.locator('tbody tr').count(),4);
    await page.screenshot({path:'test-results/mac-tv-filter.png'});
    await filters.getByRole('button',{name:'All'}).focus();
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('tbody tr').count(),7);
    await page.getByRole('textbox',{name:'Search apps'}).fill('VLC');
    assert.equal(await page.locator('tbody tr').count(),1);
    await page.getByRole('textbox',{name:'Search apps'}).fill('no-such-app');
    await page.getByText('No matching apps').waitFor();
    await page.getByRole('button',{name:'Settings',exact:true}).click();
    await page.getByRole('heading',{name:'Local server'}).waitFor();
    await page.screenshot({path:'test-results/mac-settings.png'});
    await page.getByRole('button',{name:'Stop server',exact:true}).click();
    await page.getByRole('button',{name:'Start server',exact:true}).waitFor();
    await page.getByRole('button',{name:'Start server',exact:true}).click();
    await page.getByRole('button',{name:'Stop server',exact:true}).waitFor();
    assert.deepEqual(errors,[]);
    console.log('Electron UI: search, empty results, selection, settings and server stop/start passed.');
  } finally { await client.close(); await fs.rm(temp,{recursive:true,force:true}); }
})().catch(e=>{console.error(e);process.exitCode=1;});
