pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }
rootProject.name = 'SibiStoreAndroid'
include ':core', ':app', ':tv'
include ':fixture'
project(':tv').projectDir = file('../tv/app')
